name = "gackx-web"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[pages_build_config]
build_command = "npx @cloudflare/next-on-pages"
build_output_directory = ".vercel/output/static"
